apiVersion: v1
kind: Pod
metadata:
  name: secretbox
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: secretbox
    volumeMounts:
    - mountPath: /secretstuff
      name: secret
  volumes:
  - name: secret
    secret:
      secretName: secretstuff
