apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: fake-mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
